name: Build site

on:
  pull_request:
  workflow_call:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          #cache: npm

      - name: Install dependencies
        run: npm install --force

      - name: Build
        env:
          BASE_PATH: '/orbisat-oeiras.github.io'
        run: |
          npm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/'
