name: Build site

on:
  pull_request:
  workflow_call:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Site
        uses: ./.github/actions/build
        with:
          orbipacket_token: ${{ secrets.ORBIPACKET_ACTIONS_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: './build/'
