name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build_site:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
